// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopOnline.Api.Data;

#nullable disable

namespace ShopOnline.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopOnline.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 6, 10, 12, 59, 2, 405, DateTimeKind.Utc).AddTicks(9670),
                            Description = "Electronics",
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Electronics",
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2026, 6, 10, 12, 59, 2, 406, DateTimeKind.Utc).AddTicks(142)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 6, 10, 12, 59, 2, 406, DateTimeKind.Utc).AddTicks(2403),
                            Description = "Accessories",
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Accessories",
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2026, 6, 10, 12, 59, 2, 406, DateTimeKind.Utc).AddTicks(2404)
                        });
                });

            modelBuilder.Entity("ShopOnline.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 6, 10, 12, 59, 2, 404, DateTimeKind.Utc).AddTicks(682),
                            Description = "Apple flagship",
                            IsActived = true,
                            IsDeleted = false,
                            Name = "iPhone 15",
                            Price = 999m,
                            Quantity = 10,
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2026, 6, 10, 12, 59, 2, 404, DateTimeKind.Utc).AddTicks(1155)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 6, 10, 12, 59, 2, 404, DateTimeKind.Utc).AddTicks(3534),
                            Description = "Samsung flagship",
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Samsung S24",
                            Price = 899m,
                            Quantity = 15,
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2026, 6, 10, 12, 59, 2, 404, DateTimeKind.Utc).AddTicks(3535)
                        });
                });

            modelBuilder.Entity("ShopOnline.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 6, 10, 12, 59, 2, 405, DateTimeKind.Utc).AddTicks(4306),
                            Email = "emily.johnson@x.dummyjson.com",
                            FirstName = "Emily",
                            IsActived = true,
                            IsDeleted = false,
                            LastName = "Johnson",
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2026, 6, 10, 12, 59, 2, 405, DateTimeKind.Utc).AddTicks(4788)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 6, 10, 12, 59, 2, 405, DateTimeKind.Utc).AddTicks(7050),
                            Email = "michael.williams@x.dummyjson.com",
                            FirstName = "Michael",
                            IsActived = true,
                            IsDeleted = false,
                            LastName = "Williams",
                            UpdatedBy = "System",
                            UpdatedDate = new DateTime(2026, 6, 10, 12, 59, 2, 405, DateTimeKind.Utc).AddTicks(7051)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
