// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopOnline.Api.Data;

#nullable disable

namespace ShopOnline.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129040316_AddPaymentTable")]
    partial class AddPaymentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopOnline.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 29, 4, 3, 15, 651, DateTimeKind.Utc).AddTicks(9943),
                            Description = "Electronics",
                            Name = "Electronics",
                            UpdatedDate = new DateTime(2026, 1, 29, 4, 3, 15, 651, DateTimeKind.Utc).AddTicks(9943)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 29, 4, 3, 15, 651, DateTimeKind.Utc).AddTicks(9945),
                            Description = "Accessories",
                            Name = "Accessories",
                            UpdatedDate = new DateTime(2026, 1, 29, 4, 3, 15, 651, DateTimeKind.Utc).AddTicks(9946)
                        });
                });

            modelBuilder.Entity("ShopOnline.Api.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayPalCaptureId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayPalOrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ShopOnline.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Apple flagship",
                            Name = "iPhone 15",
                            Price = 999m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            Description = "Samsung flagship",
                            Name = "Samsung S24",
                            Price = 899m,
                            Quantity = 15
                        });
                });

            modelBuilder.Entity("ShopOnline.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 29, 4, 3, 15, 651, DateTimeKind.Utc).AddTicks(9922),
                            Email = "emily.johnson@x.dummyjson.com",
                            FirstName = "Emily",
                            LastName = "Johnson",
                            UpdatedDate = new DateTime(2026, 1, 29, 4, 3, 15, 651, DateTimeKind.Utc).AddTicks(9922)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 29, 4, 3, 15, 651, DateTimeKind.Utc).AddTicks(9925),
                            Email = "michael.williams@x.dummyjson.com",
                            FirstName = "Michael",
                            LastName = "Williams",
                            UpdatedDate = new DateTime(2026, 1, 29, 4, 3, 15, 651, DateTimeKind.Utc).AddTicks(9925)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
